server:
  port: 8081
  servlet:
    context-path: /v1

spring:
  datasource:
    username: root
    password: iamdtcdzt
    url: jdbc:mysql://1.15.227.166:3306/wenshu1?characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    jdbc:
      initialize-schema: embedded
      schema: classpath:org/springframework/session/jdbc/schema-mysql.sql
      table-name: SPRING_SESSION
    timeout: 1
    store-type: jdbc
  data:
    solr:
      host: http://solr:SolrRocks@10.10.22.60:80/solr
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    root: info
    com.lrm: debug
  file:
    name: log/blog.log


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

management:
  health:
    solr:
      enabled: false

